### ISSUE TITLE
[WEB SERVER]

### ISSUE THREAD

**Issue by LeonardBesseau** [PRO-Stonks/Projet_Stonks#21]
Need to add product functionalities.
Product
Element
Event
Location

Need to implement 
- route
- controller
- model

Need also to add test

**Comment by K-do** [comment]
Schemas and tests for Location / Product and Element have been added in branch fb-server-product.

**Comment by K-do** [comment]
I'll keep working on Product routes and derivate functionalities

**Comment by LeonardBesseau** [comment]
Added event model + test.
Will later add auto journaling when user connect but otherwise will wait until product and order are added into the branch

**Comment by LeonardBesseau** [comment]
Found some idea of test to add to authController. Marked them as to do Will do later. Created #22 to follow on that later

**Comment by K-do** [comment]
Product controller, product routes and tests have been implemented in branch fb-server-product

**Comment by K-do** [comment]
I'll continue with the routes element and location

**Comment by K-do** [comment]
location route, controller and tests implemented in branch fb-server-product

**Comment by K-do** [comment]
element route, controller and tests implemented in branch fb-server-product
tests have been improved too

Work on branch fb-server-product is done, I'll open a PR.

**Comment by K-do** [comment]
doc to do
