### ISSUE TITLE
Delete response should have no body

### ISSUE THREAD

**Issue by LeonardBesseau** [PRO-Stonks/Projet_Stonks#49]
![image](https://user-images.githubusercontent.com/52856615/114834142-91cfb880-9dd0-11eb-84e7-4e2eded2192e.png)
Actually we send back a 204 with a body but a 204 response should not have a body and if there is a body, it is usually discarded.

**Comment by LeonardBesseau** [comment]
Will remove all body from 204 response

**Comment by K-do** [comment]
Approved and merged
